name: WPScan Workflow

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      RAUL_MOIS_DB_PASS: ${{ secrets.RAUL_MOIS_DB_PASS }}
      RAUL_MOIS_ROOT_PASS: ${{ secrets.RAUL_MOIS_ROOT_PASS }}

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Start WP docker
        run: docker compose up -d

      - name: Wait for wp to be ready (debug)
        run: |
          echo "Waiting for WordPress to be ready..."
          sleep 5

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Create admin user using WP-CLI
        run: |
          docker exec wordpress bash -c "
            apt-get update && apt-get install -y less mariadb-client
          "
          docker exec wordpress bash -c "
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
            chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
          "
          docker exec wordpress bash -c "
            wp core install \
              --url='http://localhost:8080' \
              --title='Test Site' \
              --admin_user='admin' \
              --admin_password='password123' \
              --admin_email='admin@example.com' \
              --path='/var/www/html' \
              --allow-root
          "

      - name: Activate vulnerable theme
        run: |
          docker exec -w /var/www/html wordpress wp theme activate twentyseventeen --allow-root

      - name: Activate vulnerable plugin
        run: |
          docker exec -w /var/www/html wordpress wp plugin activate contact-form-7 --allow-root

      - name: Install WPScan
        run: sudo gem install wpscan

      - name: Run WPScan
        env:
          WPSCAN_API_TOKEN: ${{ secrets.RAUL_MOIS_WPSCAN_API }}
        run: |
          docker run --rm --network host wpscanteam/wpscan \
            --url http://localhost:8080 \
            --enumerate vp,vt,cb,u \
            --disable-tls-checks \
            --random-user-agent 
            --api-token $WPSCAN_API_TOKEN || EXIT_CODE=$?
          echo "WPScan exited with code $EXIT_CODE (5 = vulns found)"
          exit 0