name: WPScan Workflow

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      RAUL_MOIS_DB_PASS: ${{ secrets.RAUL_MOIS_DB_PASS }}
      RAUL_MOIS_ROOT_PASS: ${{ secrets.RAUL_MOIS_ROOT_PASS }}

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Start WP on docker
        run: docker compose up -d
        
      - name: Install to finish WordPress setup through CLI
        run: |
          docker exec wordpress wp core install \
            --url="http://localhost:8080" \
            --title="WPscan Site" \
            --admin_user=admin \
            --admin_password=cool_password_123 \
            --admin_email=admin@admin.com \
            --skip-email

      - name: Wait for WP
        run: |
          echo "Waiting for WordPress..."
          for i in {1..30}; do
            curl -s http://localhost:8080 > /dev/null && break
            sleep 5
          done

      - name: Install WPScan
        run: |
          sudo gem install wpscan

      - name: Run WPScan inside Docker
        run: |
          docker run --rm --network container:$(docker ps -qf "name=wordpress") wpscanteam/wpscan \
            --url http://localhost \
            --enumerate vp,vt,cb,u \
            --disable-tls-checks \
            --random-user-agent \
            --force