name: WPScan Workflow

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      RAUL_MOIS_DB_PASS: ${{ secrets.RAUL_MOIS_DB_PASS }}
      RAUL_MOIS_ROOT_PASS: ${{ secrets.RAUL_MOIS_ROOT_PASS }}

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Start WP docker
        run: docker compose up -d

      - name: Wait for WP install to complete
        run: |
          echo "Waiting for install.php to go away..."
          for i in {1..30}; do
            ! curl -s http://localhost:8080/wp-admin/install.php | grep -q "language-continue" && break
            sleep 5
          done

      - name: Install WPScan
        run: sudo gem install wpscan

      - name: Run WPScan
        run: |
          docker run --rm --network host wpscanteam/wpscan \
            --url http://localhost:8080 \
            --enumerate vp,vt,cb,u \
            --disable-tls-checks \
            --random-user-agent \
            --force